# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 10:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('last_update_date',)},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('purchase_date',)},
        ),
        migrations.AddField(
            model_name='car',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 2, 10, 46, 8, 647884, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturing_year',
            field=models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016),
        ),
        migrations.AlterField(
            model_name='carmaker',
            name='manufacturer',
            field=models.CharField(choices=[('BMW', 'Bayerische Motoren Werke'), ('Mercedes-Benz', 'Mercedes-Benz'), ('VW', 'Volkswagen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='web_shop_api.Car'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='credit_card_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
