# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('last_update_date',)},
        ),
        migrations.AddField(
            model_name='car',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 21, 11, 50, 52, 376580, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
