# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_api', '0005_auto_20160121_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='web_shop_api.Car'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='credit_card_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
