# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_api', '0008_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Ethanol (FFV, E85 etc.)', 'Ethanol (FFV, E85 etc.)'), ('Hybrid', 'Hybrid'), ('Natural Gas', 'Natural Gas'), ('Hydrogen', 'Hydrogen'), ('Other', 'Other')], default='Petrol', max_length=30, null=True),
        ),
    ]
